-- GENERATED by terrateam_catalog_cli from api_schemas/stategraph/terrateam_tables.json.
-- DO NOT EDIT -- run `make -C code generate-api-types` to regenerate.
-- Column-level SELECT grants for the least-privilege FDW role on the
-- terrateam database. Column-level, not table-level: a table-level grant
-- would let the role read the credential columns the catalog excludes,
-- collapsing secret-exclusion to a single layer (the foreign-table
-- definitions). Intended consumer: the terrat service's boot-time
-- convergence (revoke-then-grant after every migrate, so catalog shrinkage
-- revokes too -- see docker/stategraph/service/terrat), kept in sync by a
-- test.

grant select (branch_target, path, pull_request, workspace) on dirspace_pull_request_locks to stategraph_mql;
grant select (reconcile, schedule, updated_at, tag_query, name, repo, branch, last_tried_at) on drift_schedules to stategraph_mql;
grant select (branch, work_manifest) on drift_work_manifests to stategraph_mql;
grant select (approver, created_at, sha, pull_request, token) on gate_approvals to stategraph_mql;
grant select (created_at, dir, gate, sha, workspace, pull_request, name, token) on gates to stategraph_mql;
grant select (base_sha, path, repository, sha, workspace, lock_policy, branch_target) on github_change_dirspaces to stategraph_mql;
grant select (id, installation_id, name, owner, updated_at, setup) on github_installation_repositories to stategraph_mql;
grant select (created_at, id, login, org, state, target_type, updated_at, account_status, trial_ends_at, tier, last_suspended_by, last_suspended_at, last_unsuspended_by, last_unsuspended_at, installed_by, uninstalled_by, uninstalled_at) on github_installations to stategraph_mql;
grant select (installation_id, core_id) on github_installations_map to stategraph_mql;
grant select (repository, pull_number, unlocked_at) on github_pull_request_latest_unlocks to stategraph_mql;
grant select (base_branch, base_sha, branch, pull_number, repository, sha, state, merged_sha, merged_at, title, username, created_at) on github_pull_requests to stategraph_mql;
grant select (repository_id, pull_number, core_id) on github_pull_requests_map to stategraph_mql;
grant select (repository_id, core_id) on github_repositories_map to stategraph_mql;
grant select (base_sha, completed_at, created_at, id, pull_number, repository, run_id, run_type, sha, state, tag_query, username, dirspaces, run_kind, environment, runs_on, installation_id, repo_owner, repo_name, branch) on github_work_manifests to stategraph_mql;
grant select (base_sha, path, repository, sha, workspace, lock_policy, branch_target) on gitlab_change_dirspaces to stategraph_mql;
grant select (created_at, id, installation_id, name, owner, updated_at, setup) on gitlab_installation_repositories to stategraph_mql;
grant select (account_status, created_at, id, name, state, tier, trial_ends_at) on gitlab_installations to stategraph_mql;
grant select (installation_id, core_id) on gitlab_installations_map to stategraph_mql;
grant select (repository, pull_number, unlocked_at) on gitlab_pull_request_latest_unlocks to stategraph_mql;
grant select (base_branch, base_sha, branch, merged_at, merged_sha, pull_number, repository, sha, state, title, username) on gitlab_pull_requests to stategraph_mql;
grant select (repository_id, pull_number, core_id) on gitlab_pull_requests_map to stategraph_mql;
grant select (repository_id, core_id) on gitlab_repositories_map to stategraph_mql;
grant select (base_sha, completed_at, created_at, id, pull_number, repository, run_id, run_type, sha, state, tag_query, username, dirspaces, run_kind, environment, runs_on, installation_id, repo_owner, repo_name, branch) on gitlab_work_manifests to stategraph_mql;
grant select (path, work_manifest, workspace, has_changes, created_at) on plans to stategraph_mql;
grant select (pull_request, stacks) on pull_request_stacks to stategraph_mql;
grant select (sha, created_at, data, installation, kind, repo, branch) on repo_configs to stategraph_mql;
grant select (path, work_manifest, workflow_idx, workspace) on work_manifest_dirspaceflows to stategraph_mql;
grant select (path, success, work_manifest, workspace) on work_manifest_results to stategraph_mql;
grant select (created_at, idx, ignore_errors, payload, scope, step, success, work_manifest) on workflow_step_outputs to stategraph_mql;
