-- GENERATED by terrateam_catalog_cli from api_schemas/stategraph/terrateam_tables.json.
-- DO NOT EDIT -- run `make -C code generate-api-types` to regenerate.
-- Foreign-table definitions only; the extension/server/user-mapping/schema
-- preamble is owned by the intended consumer, the boot-time FDW reconcile.
-- Drop+recreate is cheap (foreign tables are metadata only) and keeps the declared columns exactly in sync with
-- the catalog on every boot.

-- provider: shared
drop foreign table if exists terrateam.dirspace_pull_request_locks;
create foreign table terrateam.dirspace_pull_request_locks (
  branch_target text,
  path text,
  pull_request uuid,
  workspace text
) server terrateam_fdw options (schema_name 'public', table_name 'dirspace_pull_request_locks');

-- provider: shared
drop foreign table if exists terrateam.drift_schedules;
create foreign table terrateam.drift_schedules (
  reconcile boolean,
  schedule text,
  updated_at timestamptz,
  tag_query text,
  name text,
  repo uuid,
  branch text,
  last_tried_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'drift_schedules');

-- provider: shared
drop foreign table if exists terrateam.drift_work_manifests;
create foreign table terrateam.drift_work_manifests (
  branch text,
  work_manifest uuid
) server terrateam_fdw options (schema_name 'public', table_name 'drift_work_manifests');

-- provider: shared
drop foreign table if exists terrateam.gate_approvals;
create foreign table terrateam.gate_approvals (
  approver text,
  created_at timestamptz,
  sha text,
  pull_request uuid,
  token text
) server terrateam_fdw options (schema_name 'public', table_name 'gate_approvals');

-- provider: shared
drop foreign table if exists terrateam.gates;
create foreign table terrateam.gates (
  created_at timestamptz,
  dir text,
  gate jsonb,
  sha text,
  workspace text,
  pull_request uuid,
  name text,
  token text
) server terrateam_fdw options (schema_name 'public', table_name 'gates');

-- provider: github
drop foreign table if exists terrateam.github_change_dirspaces;
create foreign table terrateam.github_change_dirspaces (
  base_sha text,
  path text,
  repository bigint,
  sha text,
  workspace text,
  lock_policy text,
  branch_target text
) server terrateam_fdw options (schema_name 'public', table_name 'github_change_dirspaces');

-- provider: github
drop foreign table if exists terrateam.github_installation_repositories;
create foreign table terrateam.github_installation_repositories (
  id bigint,
  installation_id bigint,
  name text,
  owner text,
  updated_at timestamptz,
  setup boolean
) server terrateam_fdw options (schema_name 'public', table_name 'github_installation_repositories');

-- provider: github
drop foreign table if exists terrateam.github_installations;
create foreign table terrateam.github_installations (
  created_at timestamptz,
  id bigint,
  login text,
  org uuid,
  state text,
  target_type text,
  updated_at timestamptz,
  account_status text,
  trial_ends_at date,
  tier text,
  last_suspended_by text,
  last_suspended_at timestamptz,
  last_unsuspended_by text,
  last_unsuspended_at timestamptz,
  installed_by text,
  uninstalled_by text,
  uninstalled_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'github_installations');

-- provider: github
drop foreign table if exists terrateam.github_installations_map;
create foreign table terrateam.github_installations_map (
  installation_id bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'github_installations_map');

-- provider: github
drop foreign table if exists terrateam.github_pull_request_latest_unlocks;
create foreign table terrateam.github_pull_request_latest_unlocks (
  repository bigint,
  pull_number bigint,
  unlocked_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'github_pull_request_latest_unlocks');

-- provider: github
drop foreign table if exists terrateam.github_pull_requests;
create foreign table terrateam.github_pull_requests (
  base_branch text,
  base_sha text,
  branch text,
  pull_number bigint,
  repository bigint,
  sha text,
  state text,
  merged_sha text,
  merged_at timestamptz,
  title text,
  username text,
  created_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'github_pull_requests');

-- provider: github
drop foreign table if exists terrateam.github_pull_requests_map;
create foreign table terrateam.github_pull_requests_map (
  repository_id bigint,
  pull_number bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'github_pull_requests_map');

-- provider: github
drop foreign table if exists terrateam.github_repositories_map;
create foreign table terrateam.github_repositories_map (
  repository_id bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'github_repositories_map');

-- provider: github
drop foreign table if exists terrateam.github_work_manifests;
create foreign table terrateam.github_work_manifests (
  base_sha text,
  completed_at timestamptz,
  created_at timestamptz,
  id uuid,
  pull_number bigint,
  repository bigint,
  run_id text,
  run_type text,
  sha text,
  state text,
  tag_query text,
  username text,
  dirspaces jsonb,
  run_kind text,
  environment text,
  runs_on jsonb,
  installation_id bigint,
  repo_owner text,
  repo_name text,
  branch text
) server terrateam_fdw options (schema_name 'public', table_name 'github_work_manifests');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_change_dirspaces;
create foreign table terrateam.gitlab_change_dirspaces (
  base_sha text,
  path text,
  repository bigint,
  sha text,
  workspace text,
  lock_policy text,
  branch_target text
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_change_dirspaces');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_installation_repositories;
create foreign table terrateam.gitlab_installation_repositories (
  created_at timestamptz,
  id bigint,
  installation_id bigint,
  name text,
  owner text,
  updated_at timestamptz,
  setup boolean
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_installation_repositories');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_installations;
create foreign table terrateam.gitlab_installations (
  account_status text,
  created_at timestamptz,
  id bigint,
  name text,
  state text,
  tier text,
  trial_ends_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_installations');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_installations_map;
create foreign table terrateam.gitlab_installations_map (
  installation_id bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_installations_map');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_pull_request_latest_unlocks;
create foreign table terrateam.gitlab_pull_request_latest_unlocks (
  repository bigint,
  pull_number bigint,
  unlocked_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_pull_request_latest_unlocks');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_pull_requests;
create foreign table terrateam.gitlab_pull_requests (
  base_branch text,
  base_sha text,
  branch text,
  merged_at timestamptz,
  merged_sha text,
  pull_number bigint,
  repository bigint,
  sha text,
  state text,
  title text,
  username text
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_pull_requests');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_pull_requests_map;
create foreign table terrateam.gitlab_pull_requests_map (
  repository_id bigint,
  pull_number bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_pull_requests_map');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_repositories_map;
create foreign table terrateam.gitlab_repositories_map (
  repository_id bigint,
  core_id uuid
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_repositories_map');

-- provider: gitlab
drop foreign table if exists terrateam.gitlab_work_manifests;
create foreign table terrateam.gitlab_work_manifests (
  base_sha text,
  completed_at timestamptz,
  created_at timestamptz,
  id uuid,
  pull_number bigint,
  repository bigint,
  run_id text,
  run_type text,
  sha text,
  state text,
  tag_query text,
  username text,
  dirspaces jsonb,
  run_kind text,
  environment text,
  runs_on jsonb,
  installation_id bigint,
  repo_owner text,
  repo_name text,
  branch text
) server terrateam_fdw options (schema_name 'public', table_name 'gitlab_work_manifests');

-- provider: shared
drop foreign table if exists terrateam.plans;
create foreign table terrateam.plans (
  path text,
  work_manifest uuid,
  workspace text,
  has_changes boolean,
  created_at timestamptz
) server terrateam_fdw options (schema_name 'public', table_name 'plans');

-- provider: shared
drop foreign table if exists terrateam.pull_request_stacks;
create foreign table terrateam.pull_request_stacks (
  pull_request uuid,
  stacks jsonb
) server terrateam_fdw options (schema_name 'public', table_name 'pull_request_stacks');

-- provider: shared
drop foreign table if exists terrateam.repo_configs;
create foreign table terrateam.repo_configs (
  sha text,
  created_at timestamptz,
  data jsonb,
  installation uuid,
  kind text,
  repo uuid,
  branch text
) server terrateam_fdw options (schema_name 'public', table_name 'repo_configs');

-- provider: shared
drop foreign table if exists terrateam.work_manifest_dirspaceflows;
create foreign table terrateam.work_manifest_dirspaceflows (
  path text,
  work_manifest uuid,
  workflow_idx smallint,
  workspace text
) server terrateam_fdw options (schema_name 'public', table_name 'work_manifest_dirspaceflows');

-- provider: shared
drop foreign table if exists terrateam.work_manifest_results;
create foreign table terrateam.work_manifest_results (
  path text,
  success boolean,
  work_manifest uuid,
  workspace text
) server terrateam_fdw options (schema_name 'public', table_name 'work_manifest_results');

-- provider: shared
drop foreign table if exists terrateam.workflow_step_outputs;
create foreign table terrateam.workflow_step_outputs (
  created_at timestamptz,
  idx smallint,
  ignore_errors boolean,
  payload jsonb,
  scope jsonb,
  step text,
  success boolean,
  work_manifest uuid
) server terrateam_fdw options (schema_name 'public', table_name 'workflow_step_outputs');
