(* GENERATED by terrateam_catalog_cli from api_schemas/stategraph/terrateam_tables.json.
   DO NOT EDIT -- run `make -C code generate-api-types` to regenerate. *)

let tables =
  Mql_to_pgsql.Schema.
    [
      Table.make
        ~name:"dirspace_pull_request_locks"
        Column.
          [
            make ~name:"branch_target" ~type_:Type_.Text ();
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"pull_request" ~type_:Type_.Uuid ();
            make ~name:"workspace" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"drift_schedules"
        Column.
          [
            make ~name:"reconcile" ~type_:Type_.Bool ();
            make ~name:"schedule" ~type_:Type_.Text ();
            make ~name:"updated_at" ~type_:Type_.Timestamptz ();
            make ~name:"tag_query" ~type_:Type_.Text ();
            make ~name:"name" ~type_:Type_.Text ();
            make ~name:"repo" ~type_:Type_.Uuid ();
            make ~name:"branch" ~type_:Type_.Text ();
            make ~name:"last_tried_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"drift_work_manifests"
        Column.
          [
            make ~name:"branch" ~type_:Type_.Text ();
            make ~name:"work_manifest" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"gate_approvals"
        Column.
          [
            make ~name:"approver" ~type_:Type_.Text ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"pull_request" ~type_:Type_.Uuid ();
            make ~name:"token" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"gates"
        Column.
          [
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"dir" ~type_:Type_.Text ();
            make ~name:"gate" ~type_:Type_.Jsonb ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"workspace" ~type_:Type_.Text ();
            make ~name:"pull_request" ~type_:Type_.Uuid ();
            make ~name:"name" ~type_:Type_.Text ();
            make ~name:"token" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"github_change_dirspaces"
        Column.
          [
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"workspace" ~type_:Type_.Text ();
            make ~name:"lock_policy" ~type_:Type_.Text ();
            make ~name:"branch_target" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"github_installation_repositories"
        Column.
          [
            make ~name:"id" ~type_:Type_.Bigint ();
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"name" ~type_:Type_.Text ();
            make ~name:"owner" ~type_:Type_.Text ();
            make ~name:"updated_at" ~type_:Type_.Timestamptz ();
            make ~name:"setup" ~type_:Type_.Bool ();
          ];
      Table.make
        ~name:"github_installations"
        Column.
          [
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"id" ~type_:Type_.Bigint ();
            make ~name:"login" ~type_:Type_.Text ();
            make ~name:"org" ~type_:Type_.Uuid ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"target_type" ~type_:Type_.Text ();
            make ~name:"updated_at" ~type_:Type_.Timestamptz ();
            make ~name:"account_status" ~type_:Type_.Text ();
            make ~name:"trial_ends_at" ~type_:(Type_.Complex "date") ();
            make ~name:"tier" ~type_:Type_.Text ();
            make ~name:"last_suspended_by" ~type_:Type_.Text ();
            make ~name:"last_suspended_at" ~type_:Type_.Timestamptz ();
            make ~name:"last_unsuspended_by" ~type_:Type_.Text ();
            make ~name:"last_unsuspended_at" ~type_:Type_.Timestamptz ();
            make ~name:"installed_by" ~type_:Type_.Text ();
            make ~name:"uninstalled_by" ~type_:Type_.Text ();
            make ~name:"uninstalled_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"github_installations_map"
        Column.
          [
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"github_pull_request_latest_unlocks"
        Column.
          [
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"unlocked_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"github_pull_requests"
        Column.
          [
            make ~name:"base_branch" ~type_:Type_.Text ();
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"branch" ~type_:Type_.Text ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"merged_sha" ~type_:Type_.Text ();
            make ~name:"merged_at" ~type_:Type_.Timestamptz ();
            make ~name:"title" ~type_:Type_.Text ();
            make ~name:"username" ~type_:Type_.Text ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"github_pull_requests_map"
        Column.
          [
            make ~name:"repository_id" ~type_:Type_.Bigint ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"github_repositories_map"
        Column.
          [
            make ~name:"repository_id" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"github_work_manifests"
        Column.
          [
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"completed_at" ~type_:Type_.Timestamptz ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"id" ~type_:Type_.Uuid ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"run_id" ~type_:Type_.Text ();
            make ~name:"run_type" ~type_:Type_.Text ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"tag_query" ~type_:Type_.Text ();
            make ~name:"username" ~type_:Type_.Text ();
            make ~name:"dirspaces" ~type_:Type_.Jsonb ();
            make ~name:"run_kind" ~type_:Type_.Text ();
            make ~name:"environment" ~type_:Type_.Text ();
            make ~name:"runs_on" ~type_:Type_.Jsonb ();
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"repo_owner" ~type_:Type_.Text ();
            make ~name:"repo_name" ~type_:Type_.Text ();
            make ~name:"branch" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"gitlab_change_dirspaces"
        Column.
          [
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"workspace" ~type_:Type_.Text ();
            make ~name:"lock_policy" ~type_:Type_.Text ();
            make ~name:"branch_target" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"gitlab_installation_repositories"
        Column.
          [
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"id" ~type_:Type_.Bigint ();
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"name" ~type_:Type_.Text ();
            make ~name:"owner" ~type_:Type_.Text ();
            make ~name:"updated_at" ~type_:Type_.Timestamptz ();
            make ~name:"setup" ~type_:Type_.Bool ();
          ];
      Table.make
        ~name:"gitlab_installations"
        Column.
          [
            make ~name:"account_status" ~type_:Type_.Text ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"id" ~type_:Type_.Bigint ();
            make ~name:"name" ~type_:Type_.Text ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"tier" ~type_:Type_.Text ();
            make ~name:"trial_ends_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"gitlab_installations_map"
        Column.
          [
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"gitlab_pull_request_latest_unlocks"
        Column.
          [
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"unlocked_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"gitlab_pull_requests"
        Column.
          [
            make ~name:"base_branch" ~type_:Type_.Text ();
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"branch" ~type_:Type_.Text ();
            make ~name:"merged_at" ~type_:Type_.Timestamptz ();
            make ~name:"merged_sha" ~type_:Type_.Text ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"title" ~type_:Type_.Text ();
            make ~name:"username" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"gitlab_pull_requests_map"
        Column.
          [
            make ~name:"repository_id" ~type_:Type_.Bigint ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"gitlab_repositories_map"
        Column.
          [
            make ~name:"repository_id" ~type_:Type_.Bigint ();
            make ~name:"core_id" ~type_:Type_.Uuid ();
          ];
      Table.make
        ~name:"gitlab_work_manifests"
        Column.
          [
            make ~name:"base_sha" ~type_:Type_.Text ();
            make ~name:"completed_at" ~type_:Type_.Timestamptz ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"id" ~type_:Type_.Uuid ();
            make ~name:"pull_number" ~type_:Type_.Bigint ();
            make ~name:"repository" ~type_:Type_.Bigint ();
            make ~name:"run_id" ~type_:Type_.Text ();
            make ~name:"run_type" ~type_:Type_.Text ();
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"state" ~type_:Type_.Text ();
            make ~name:"tag_query" ~type_:Type_.Text ();
            make ~name:"username" ~type_:Type_.Text ();
            make ~name:"dirspaces" ~type_:Type_.Jsonb ();
            make ~name:"run_kind" ~type_:Type_.Text ();
            make ~name:"environment" ~type_:Type_.Text ();
            make ~name:"runs_on" ~type_:Type_.Jsonb ();
            make ~name:"installation_id" ~type_:Type_.Bigint ();
            make ~name:"repo_owner" ~type_:Type_.Text ();
            make ~name:"repo_name" ~type_:Type_.Text ();
            make ~name:"branch" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"plans"
        Column.
          [
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"work_manifest" ~type_:Type_.Uuid ();
            make ~name:"workspace" ~type_:Type_.Text ();
            make ~name:"has_changes" ~type_:Type_.Bool ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
          ];
      Table.make
        ~name:"pull_request_stacks"
        Column.
          [
            make ~name:"pull_request" ~type_:Type_.Uuid ();
            make ~name:"stacks" ~type_:Type_.Jsonb ();
          ];
      Table.make
        ~name:"repo_configs"
        Column.
          [
            make ~name:"sha" ~type_:Type_.Text ();
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"data" ~type_:Type_.Jsonb ();
            make ~name:"installation" ~type_:Type_.Uuid ();
            make ~name:"kind" ~type_:Type_.Text ();
            make ~name:"repo" ~type_:Type_.Uuid ();
            make ~name:"branch" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"work_manifest_dirspaceflows"
        Column.
          [
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"work_manifest" ~type_:Type_.Uuid ();
            make ~name:"workflow_idx" ~type_:Type_.Smallint ();
            make ~name:"workspace" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"work_manifest_results"
        Column.
          [
            make ~name:"path" ~type_:Type_.Text ();
            make ~name:"success" ~type_:Type_.Bool ();
            make ~name:"work_manifest" ~type_:Type_.Uuid ();
            make ~name:"workspace" ~type_:Type_.Text ();
          ];
      Table.make
        ~name:"workflow_step_outputs"
        Column.
          [
            make ~name:"created_at" ~type_:Type_.Timestamptz ();
            make ~name:"idx" ~type_:Type_.Smallint ();
            make ~name:"ignore_errors" ~type_:Type_.Bool ();
            make ~name:"payload" ~type_:Type_.Jsonb ();
            make ~name:"scope" ~type_:Type_.Jsonb ();
            make ~name:"step" ~type_:Type_.Text ();
            make ~name:"success" ~type_:Type_.Bool ();
            make ~name:"work_manifest" ~type_:Type_.Uuid ();
          ];
    ]
