(library
 (name sgs_service_users)
 (wrapped false)
 (libraries
  abb
  abbs
  brtl
  brtl_ep
  containers
  logs
  pgsql_io
  pgsql_pool
  sg_caps
  sg_caps_json
  sg_caps_ops
  sgs_api
  sgs_config
  sgs_eplib
  sgs_service
  sgs_service_config
  sgs_service_storage
  sgs_service_tenants
  sgs_svc_mngr
  sgs_storage
  sgs_tenant
  sgs_user
  uuidm
  yojson)
 (preprocessor_deps
  (glob_files_rec sql/*))
 (preprocess
  (pps ppx_blob)))
