(* Generator for the terrateam table catalog.

   Reads api_schemas/stategraph/terrateam_tables.json -- the allow-list of
   terrateam tables and columns readable over the FDW bridge -- and emits the
   three artifacts that must never drift apart:

   - <name>.ml        the Mql_to_pgsql.Schema.Table.t fragment the MQL
                      endpoint appends to its schema when orchestration is on
   - fdw_tables.sql   drop+create foreign-table DDL applied by the boot-time
                      FDW reconcile
   - fdw_grants.sql   SELECT grants for the least-privilege FDW role, applied
                      as a terrat migration (kept in sync by a test)

   Secret-safety is by construction: a column not in the catalog appears in no
   artifact, so credential columns are not even declared at the FDW layer.
   Tests over the catalog enforce that no secret-shaped column sneaks in. *)

module Cat = struct
  type column = {
    name : string;
    type_ : string;
  }

  type table = {
    name : string;
    provider : string;
    columns : column list;
  }

  (* Table and column names reach SQL emission verbatim, so hold them to
     strict lower_snake identifiers rather than trusting quoting. *)
  let is_ident s =
    (not (CCString.is_empty s))
    && (match s.[0] with
      | 'a' .. 'z' | '_' -> true
      | _ -> false)
    && CCString.for_all
         (function
           | 'a' .. 'z' | '0' .. '9' | '_' -> true
           | _ -> false)
         s

  let member_string k assoc =
    match Sln_list.String.assoc_opt k assoc with
    | Some (`String s) -> s
    | Some _ -> failwith (Printf.sprintf "field %S must be a string" k)
    | None -> failwith (Printf.sprintf "missing field %S" k)

  let column_of_json = function
    | `Assoc assoc ->
        let name = member_string "name" assoc in
        if not (is_ident name) then failwith (Printf.sprintf "invalid column name %S" name);
        { name; type_ = member_string "type" assoc }
    | _ -> failwith "each column must be an object"

  let table_of_json = function
    | `Assoc assoc ->
        let name = member_string "name" assoc in
        if not (is_ident name) then failwith (Printf.sprintf "invalid table name %S" name);
        let provider = member_string "provider" assoc in
        (match provider with
        | "github" | "gitlab" | "shared" -> ()
        | p -> failwith (Printf.sprintf "table %s: unknown provider %S" name p));
        let columns =
          match Sln_list.String.assoc_opt "columns" assoc with
          | Some (`List (_ :: _ as l)) -> CCList.map column_of_json l
          | Some (`List []) -> failwith (Printf.sprintf "table %s has no columns" name)
          | _ -> failwith (Printf.sprintf "table %s: columns must be a non-empty list" name)
        in
        { name; provider; columns }
    | _ -> failwith "each table must be an object"

  let assert_no_dups what names =
    let sorted = CCList.sort CCString.compare names in
    CCList.iter2
      (fun a b -> if CCString.equal a b then failwith (Printf.sprintf "duplicate %s %S" what a))
      (CCList.take (CCList.length sorted - 1) sorted)
      (CCList.drop 1 sorted)

  let load path =
    match Yojson.Safe.from_file path with
    | `Assoc assoc -> (
        match Sln_list.String.assoc_opt "tables" assoc with
        | Some (`List l) ->
            let tables = CCList.map table_of_json l in
            assert_no_dups "table" (CCList.map (fun (t : table) -> t.name) tables);
            CCList.iter
              (fun (t : table) ->
                assert_no_dups
                  (Printf.sprintf "column in table %s" t.name)
                  (CCList.map (fun (c : column) -> c.name) t.columns))
              tables;
            tables
        | _ -> failwith "top-level object must have a \"tables\" list")
    | _ -> failwith "top-level JSON must be an object"
end

(* One catalog type maps to exactly one DDL type and one MQL type; an unknown
   type fails the build rather than guessing. *)
let ddl_type = function
  | "text" -> "text"
  | "bigint" -> "bigint"
  | "uuid" -> "uuid"
  | "boolean" -> "boolean"
  | "timestamptz" -> "timestamptz"
  | "jsonb" -> "jsonb"
  | "smallint" -> "smallint"
  | "date" -> "date"
  | t -> failwith (Printf.sprintf "unknown catalog type %S" t)

let mql_type = function
  | "text" -> "Type_.Text"
  | "bigint" -> "Type_.Bigint"
  | "uuid" -> "Type_.Uuid"
  | "boolean" -> "Type_.Bool"
  | "timestamptz" -> "Type_.Timestamptz"
  | "jsonb" -> "Type_.Jsonb"
  | "smallint" -> "Type_.Smallint"
  | "date" -> {|(Type_.Complex "date")|}
  | t -> failwith (Printf.sprintf "unknown catalog type %S" t)

module Emit = struct
  open Cat

  let header ~comment ~regenerate =
    Printf.sprintf
      {|%s GENERATED by terrateam_catalog_cli from api_schemas/stategraph/terrateam_tables.json.
%s DO NOT EDIT -- run `make -C code %s` to regenerate.
|}
      comment
      comment
      regenerate

  let ml tables =
    let column (c : column) =
      Printf.sprintf {|          make ~name:"%s" ~type_:%s ();
|} c.name (mql_type c.type_)
    in
    let table (t : table) =
      Printf.sprintf
        {|      Table.make ~name:"%s"
        Column.[
%s        ];
|}
        t.name
        (CCString.concat "" (CCList.map column t.columns))
    in
    {|(* GENERATED by terrateam_catalog_cli from api_schemas/stategraph/terrateam_tables.json.
   DO NOT EDIT -- run `make -C code generate-api-types` to regenerate. *)

let tables =
  Mql_to_pgsql.Schema.(
    [
|}
    ^ CCString.concat "" (CCList.map table tables)
    ^ {|    ])
|}

  let fdw_tables tables =
    let table (t : table) =
      Printf.sprintf
        {|
-- provider: %s
drop foreign table if exists terrateam.%s;
create foreign table terrateam.%s (
%s
) server terrateam_fdw options (schema_name 'public', table_name '%s');
|}
        t.provider
        t.name
        t.name
        (CCString.concat
           ",\n"
           (CCList.map
              (fun (c : column) -> Printf.sprintf "  %s %s" c.name (ddl_type c.type_))
              t.columns))
        t.name
    in
    header ~comment:"--" ~regenerate:"generate-api-types"
    ^ {|-- Foreign-table definitions only; the extension/server/user-mapping/schema
-- preamble is owned by the intended consumer, the boot-time FDW reconcile.
-- Drop+recreate is cheap (foreign tables are metadata only) and keeps the declared columns exactly in sync with
-- the catalog on every boot.
|}
    ^ CCString.concat "" (CCList.map table tables)

  let fdw_grants tables =
    let table (t : table) =
      Printf.sprintf
        {|grant select (%s) on %s to stategraph_mql;
|}
        (CCString.concat ", " (CCList.map (fun (c : column) -> c.name) t.columns))
        t.name
    in
    header ~comment:"--" ~regenerate:"generate-api-types"
    ^ {|-- Column-level SELECT grants for the least-privilege FDW role on the
-- terrateam database. Column-level, not table-level: a table-level grant
-- would let the role read the credential columns the catalog excludes,
-- collapsing secret-exclusion to a single layer (the foreign-table
-- definitions). Intended consumer: the terrat service's boot-time
-- convergence (revoke-then-grant after every migrate, so catalog shrinkage
-- revokes too -- see docker/stategraph/service/terrat), kept in sync by a
-- test.

|}
    ^ CCString.concat "" (CCList.map table tables)
end

let write_file dir file content =
  let oc = open_out (Filename.concat dir file) in
  output_string oc content;
  close_out oc

let convert input name output_dir =
  let tables = Cat.load input in
  write_file output_dir (name ^ ".ml") (Emit.ml tables);
  write_file output_dir "fdw_tables.sql" (Emit.fdw_tables tables);
  write_file output_dir "fdw_grants.sql" (Emit.fdw_grants tables)

module Cmdline = struct
  module C = Cmdliner

  let input_file =
    let doc = "Input terrateam_tables.json catalog" in
    C.Arg.(required & opt (some string) None & info [ "i"; "input" ] ~doc)

  let output_name =
    let doc = "Root name for the OCaml output (e.g. sgs_terrateam_catalog)" in
    C.Arg.(required & opt (some string) None & info [ "n"; "name" ] ~doc)

  let output_dir =
    let doc = "Directory to write outputs to" in
    C.Arg.(required & opt (some string) None & info [ "output-dir" ] ~doc)

  let convert_cmd =
    let doc = "Generate the FDW DDL, MQL schema fragment, and grants" in
    C.Cmd.v
      (C.Cmd.info "convert" ~doc)
      C.Term.(const (fun i n d -> convert i n d) $ input_file $ output_name $ output_dir)

  let default_cmd = C.Term.(ret (const (`Help (`Pager, None))))
end

let () =
  let module C = Cmdliner in
  let info =
    C.Cmd.info "terrateam_catalog_cli" ~doc:"Generate FDW + MQL artifacts from the table catalog"
  in
  let cmd = C.Cmd.group info ~default:Cmdline.default_cmd [ Cmdline.convert_cmd ] in
  exit (C.Cmd.eval cmd)
